### ISSUE TITLE
The plugin breakes a colorscheme

### ISSUE THREAD

**Issue by gorsheninmv** [alec-gibson/nvim-tetris#1]
After neovim launching a colorscheme has been broken yet.
I guess the issue is the "set termguicolors" option in the nvim-tetris.vim file.

**Comment by alec-gibson** [comment]
Thanks for the bug report! That sounds like a likely cause.

Could you try the preserve-colorscheme branch and see if that fixes the issue?

**Comment by gorsheninmv** [comment]
Unfortunately, it doesn\`t work for me I can\`t see tetris figures if termguicolors is not set. My option is tmux + alacritty.
However, it might be not a good idea to set termguicolors in the plugin. I think it would be better just to check if the option is set and then to show an error message otherwise.

**Comment by alec-gibson** [comment]
I'll look at this sometime in the next couple days. Maybe I can provide ctermfg fallbacks for the guifg highlights I'm using, so the plugin is still usable without termguicolors.

**Comment by alec-gibson** [comment]
I think this is fixed now. I merged a PR from my preserve-colorscheme branch to master. Stopped setting termguicolors automatically, and also set some ctermfg fallback highlights, for configs that don't pick up guifg values. They look worse than the gui colours, but at least it's usable now :smiley:

**Comment by gorsheninmv** [comment]
Thanks! For now that works perfectly (^_^)
