### ISSUE TITLE
Tetris messing with my EndingWhiteMatch

### ISSUE THREAD

**Issue by EmilSodergren** [alec-gibson/nvim-tetris#3]
I have the following config in my .vimrc
```
hi EndingWhiteSpace ctermbg=52
match EndingWhiteSpace /\s\+\%#\@<!$/
```
This highlights ending whitespaces in a dark red color. This does not work anymore after installing nvim-tetris.

**Comment by alec-gibson** [comment]
Thanks for the bug report.

Until very recently, nvim-tetris forced termguicolors to be set. I fixed this the other day by recommending users use termguicolors in the readme, but not forcing it, and providing fallback colors if the user chooses not to. Would you mind making sure your version of nvim-tetris is completely up-to-date, and verify whether this is still an issue?

**Comment by EmilSodergren** [comment]
Ah, yes it works now. Awesome!
